### ISSUE TITLE
Scan simplisity

### ISSUE THREAD

**Issue by TrySound** [reactive-react/xreact#40]
Update functions looks like this
```js
const update = intent => {
  switch (intent.type) {
    case 'inc':
      return state => ({ count: state.count + 1 });
    case 'dec':
      return state => ({ count: state.count - 1 });
    default:
      return _ => _;
  }
}
```

Looks too noisy in comparing with redux, because require to write a function for every case. Why not just use scan and behave in the same way?

```js
const plan = (msg$) => {
  return {
    update$: msg$.scan((state, action) => {
      switch (action.type) {
        case 'inc':
          return { count: state.count + 1 };
        case 'dec':
          return { count: state.count - 1 };
        default:
          return state;
      }
    }, { count: 0 }),
    actions: {
      inc: () => ({ type: 'inc' }),
      dec: () => ({ type: 'dec' })
    }
  }
}
```

**Comment by jcouyang** [comment]
it's designed that way because xreact encourage more on FP, so function is chosen over value

compare:

a stream of functions

    -(+1)-(-1)-(+1)->

and a stream of values

    -1-0-1->

the final result may or may not be the same, because `setState` is async

    setState(state=>({ count: state.count + 1 }))

can guarantee that it use the count when the function is called

but

    setState({ count: state.count + 1 })

use the `count` when `setState` is evaluated, if any state change A kick in between `setState` eval and React actually action to set the state, the change A will be overwrited and the result will not be accurate.

the function we using here is more like the lazy eval concept in FP

plus, it will actually less noise and more readable than redux if you use some FP lib like ramda(lens), or lodash

```js
let lensCount = lens(prop('count'))
...
switch (intent.type) {
    case 'inc':
      return over(lensCount, inc);
    case 'dec':
      return over(lensCount, dec);
    default:
      return identity;
  }
```

I've documented some good practice you may need to get all the FP advantage from xreact
in wiki https://github.com/reactive-react/xreact/wiki/FRP-Best-Practice

**Comment by TrySound** [comment]
I understand. Thanks.
